swagger: "2.0"
info:
  version: "0.0.1"
  title: CRM Info
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    get:
      description: "This endpoint returns all the clients available in the database"
      operationId: "GetAllClients"
      parameters: []
      responses:
        200:
          description: "An array of clients"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ClientInfo"
      x-swagger-router-controller: "GetAllClients"
    post:
      description: "This endpoint adds a new clients to the database"
      operationId: "AddClient"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "client"
        description: "The client to be added"
        required: true
        schema:
          $ref: "#/definitions/ClientInfo"
      responses:
        200:
          description: "Add client successfully"
          schema:
            $ref: "#/definitions/AddResponse"
      x-swagger-router-controller: "AddClient"
  /client/{name}:
    get:
      x-swagger-router-controller: "GetClientByName"
      description: "Retrieve a client by name"
      operationId: "GetClientByName"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of the client to get"
        required: true
        type: "string"
      responses:
        200:
          description: "Client by name responses"
          schema:
            $ref: "#/definitions/ClientInfo"   
    delete:
      description: "Delete a client by name"
      operationId: "DeleteClientByName"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of the client to delete"
        required: true
        type: "string"
      responses:
        204:
          description: "Client deleted"
      x-swagger-router-controller:
        "DeleteClientByName"
    put:
      description: "Update a client by name"
      operationId: "UpdateClientByName"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: "Name of the client to be update"
        required: true
        type: "string"
      - name: "updated_client"
        in: "body"
        description: "The updated Client"
        required: true
        schema:
          $ref: "#/definitions/ClientInfo"
      responses:
        200:
          description: "Client updated"
          schema:
            $ref: "#/definitions/AddResponse" 
        400:
          description: "Error occurs when updated"
      x-swagger-router-controller:
        "UpdateClientByName"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ClientInfo:
    type: "object"
    properties:
      client_name:
        type: "string"
        description: "name of the client"
      client_gender:
        type: "string"
        description: "gender of the client"
      client_age:
        type: "integer"
        description: "age of the client"
      client_citizenship:
        type: "string"
        description: "citizenship of the client"
      client_email:
        type: "string"
        description: "email of the client"
      client_phone:
        type: "integer"
        description: "phone number of the client"
      client_address:
        type: "string"
        description: "address of the client"
  AddResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Id of the client added"
      message:
        type: "string"